-- ============================================================
-- 장학금 DB 시드 데이터 (CSV → SQL)
-- Supabase Dashboard > SQL Editor 에서 실행하세요.
-- PostgreSQL 커스텀 타입 캐스팅 포함 버전
-- ============================================================

BEGIN;

-- ── 고려대학교 ────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_income_level_min,qual_income_level_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026학년도 1학기 KU Pride Club 생활비 장학금 (일반유형)','고려대학교','학교법인',ARRAY['생활비']::support_category[],600000,'2026-04-01','2026-04-30','2026-05-29',282,ARRAY['재학']::enrollment_status_type[],2.0,1,6,false,ARRAY['KUPC 장학금 신청서(2026) 1부 (필수 온라인 업로드)'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1107 / scholarship@korea.ac.kr','포털 계좌정보 사전 확인 필수. 취지에 어긋나는 행동, 휴학, 제적 시 지급 제외. 생활비장학금 60만원 초과 수혜자 신청 불가.',2,'서류심사','최종발표','~2026-04-30 오후 4시','2026-05-29','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_enrollment_status,qual_major,qual_gpa_last_semester_min,qual_income_level_min,qual_income_level_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026학년도 1학기 KU Pride Club 생활비 장학금 (특별유형)','고려대학교','학교법인',ARRAY['생활비']::support_category[],600000,'2026-04-01','2026-04-30','2026-05-29',282,ARRAY['재학']::enrollment_status_type[],ARRAY['체육특기자'],2.0,1,6,false,ARRAY['KUPC 장학금 신청서(2026) 1부 (필수 온라인 업로드)'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1107 / scholarship@korea.ac.kr','포털 계좌정보 사전 확인 필수. 체육특기자 대상. 생활비장학금 60만원 초과 수혜자 신청 불가.',2,'서류심사','최종발표','~2026-04-30 오후 4시','2026-05-29','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_income_level_min,qual_income_level_max,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 미래로장학금 2차','고려대학교','학교법인',ARRAY['생활비','등록금']::support_category[],0,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],2.5,0,8,ARRAY['기초생활수급자']::special_info_type[],false,ARRAY['온라인 신청서(포털)'],'온라인(포털 KUPID)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1106 (학생지원팀)','1차 탈락자는 2차 신청 필수. 맥북 사용 시 오류 가능 → 윈도우 PC 권장. 기초생활수급자는 생활비·기숙사장학금 추가 가능.',2,'서류심사','최종발표','~2026-04-30 오후 4시','5월 중순','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 재해극복장학금','고려대학교','학교법인',ARRAY['학업장려금']::support_category[],0,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],true,ARRAY['장학금 신청서(온라인)','가족관계증명서','피해사실확인서(행정기관 발행)'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1105 (서울캠퍼스 학생지원팀)','2025-2학기~2026-1학기 자연재해(수해, 태풍 등) 피해 학생 대상. 학업보조비 장학금과 이중수혜 허용(동일 건 1회 한정).',2,'서류심사','최종발표','~2026-04-30 오후 4시 / 심사 5월 중','5월 말 예정','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_nationality,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 소망장학금','고려대학교','학교법인',ARRAY['등록금']::support_category[],0,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],'내국인',ARRAY['장애인']::special_info_type[],true,ARRAY['장학금 신청서(온라인)','장애인증명서(2026.3.1. 이후 발급분)'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1105 (서울캠퍼스 학생지원팀)','특수교육대상자 전형 입학자 또는 장애인 학생 대상. 수업료 50% 지원. 수업료지원 장학금 범위 내 이중수혜 가능.',2,'서류심사','최종발표','~2026-04-30 오후 4시 / 심사 5월 중','5월 말 예정','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_income_level_max,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 드림장학금','고려대학교','학교법인',ARRAY['등록금']::support_category[],0,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],8,ARRAY['다문화가정']::special_info_type[],false,ARRAY['장학금 신청서(온라인)','가족관계증명서','부모 국적취득증명서 또는 귀화증명서'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1105 (서울캠퍼스 학생지원팀)','다문화가정 자녀 대상 (부모 중 1인 이상 귀화). 수업료 50% 지원. 다문화인재 생활비 장학금 수혜자 및 고대가족장학금 신청자 중복 불가.',2,'서류심사','최종발표','~2026-04-30 오후 4시 / 심사 5월 중','5월 말 예정','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 고대가족장학금','고려대학교','학교법인',ARRAY['등록금']::support_category[],0,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],true,ARRAY['장학금 신청서(온라인)','형제·자매 학번','가족관계증명서'],'온라인(포털) + 외국인은 이메일/방문 병행','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1105 (서울캠퍼스 학생지원팀) / scholarship@korea.ac.kr','형제·자매가 고려대(대학원 포함)에 동시 재학 중인 학부생 대상. 수업료 50% 지원. 수업료지원 장학금 범위 내 이중수혜 가능.',2,'서류심사','최종발표','~2026-04-30 오후 4시 / 심사 5월 중','5월 말 예정','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_academic_year,qual_enrollment_status,qual_major,qual_income_level_max,qual_region,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 오픈캠퍼스장학생','고려대학교','학교법인',ARRAY['등록금']::support_category[],0,'2026-03-09','2026-04-03',2,ARRAY['4년제']::school_category_type[],ARRAY[1],ARRAY['재학']::enrollment_status_type[],ARRAY['자연계열','공학','생명과학','간호'],9,ARRAY['성북구'],false,ARRAY['장학생 신청서','자기소개서','주민등록등본','등록금납입증명서','소득구간통지서'],'방문 또는 우편 접수 (서울시 성북구 보문로 168 성북구청 10층 교육지원과)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-2241-2479 (성북구청 교육지원과)','운영기관: 성북구청. 2년간(4학기) 지급. 성북구에 1년 이상 연속 거주한 부 또는 모의 자녀인 고려대 신입생(자연계열) 대상.',2,'서류심사','최종발표(개별통보)','2026년 4월 중','확정 후 개별 통보','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_min,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 Essor(飛翔) 장학금 (A유형)','고려대학교','학교법인',ARRAY['등록금']::support_category[],1000000,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],3.75,false,ARRAY['장학금신청서','성적증명서'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1105','직전학기 성적경고 해제자 (직전학기 이전학기 성적경고 받은 자 중 직전학기 평점평균 1.75 이상인 자) 대상. 취득학점 15학점 이상, 평점평균 3.75 이상 필요.',2,'서류심사','최종발표','~2026-04-30 오후 4시','5월 중','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_min,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026-1학기 Essor(飛翔) 장학금 (B유형)','고려대학교','학교법인',ARRAY['등록금']::support_category[],500000,'2026-04-01','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],3.5,false,ARRAY['장학금신청서','성적증명서'],'온라인(포털)','https://portal.korea.ac.kr','https://www.korea.ac.kr','02-3290-1105','직전학기 성적경고 해제자 대상. 취득학점 15학점 이상, 평점평균 3.5~3.75 미만 필요.',2,'서류심사','최종발표','~2026-04-30 오후 4시','5월 중','2026-04-12',false);

-- ── 한국장학재단 ──────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_academic_year,qual_enrollment_status,qual_major,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 대통령과학장학금 국내 신규장학생 (일반 - 1학년)','한국장학재단','공공기관',ARRAY['등록금','학업장려금']::support_category[],0,'2026-04-08','2026-04-22',63,ARRAY[1],ARRAY['재학']::enrollment_status_type[],ARRAY['자연과학','공학계열'],'내국인',false,ARRAY['한국장학재단 포털 공지사항 첨부파일 참조'],'온라인(www.kosaf.go.kr → 장학금 → 국가우수장학금 → 대통령과학장학금 → 신청하기)','https://www.kosaf.go.kr','https://www.kosaf.go.kr','1599-2290 (한국장학재단)','수업료 전액 + 학업장려비 지원. 기초생활수급자는 생활비 250만원/학기 추가 지원.',1,'서류심사 및 최종발표','~2026-04-22 오후 6시','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_academic_year,qual_enrollment_status,qual_major,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 대통령과학장학금 국내 신규장학생 (일반 - 3학년)','한국장학재단','공공기관',ARRAY['등록금','학업장려금']::support_category[],0,'2026-04-08','2026-04-22',60,ARRAY[3],ARRAY['재학']::enrollment_status_type[],ARRAY['자연과학','공학계열'],'내국인',false,ARRAY['한국장학재단 포털 공지사항 첨부파일 참조'],'온라인(www.kosaf.go.kr)','https://www.kosaf.go.kr','https://www.kosaf.go.kr','1599-2290 (한국장학재단)','수업료 전액 + 학업장려비 지원. 기초생활수급자는 생활비 250만원/학기 추가 지원.',1,'서류심사 및 최종발표','~2026-04-22 오후 6시','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_academic_year,qual_enrollment_status,qual_major,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년 대통령과학장학금 국내 신규장학생 (지역추천 - 1학년)','한국장학재단','공공기관',ARRAY['등록금','학업장려금']::support_category[],0,'2026-04-08','2026-04-22',14,ARRAY[1],ARRAY['재학']::enrollment_status_type[],ARRAY['자연과학','공학계열'],'내국인',false,ARRAY['한국장학재단 포털 공지사항 첨부파일 참조'],'시·도 교육감 추천 후 별도 안내에 따라 온라인 신청(www.kosaf.go.kr)','https://www.kosaf.go.kr','https://www.kosaf.go.kr','1599-2290 (한국장학재단)','지역추천 유형은 시·도 교육감 추천자에 한해 별도 신청 안내 예정. 기초생활수급자는 생활비 250만원/학기 추가 지원.',2,'시·도 교육감 추천','서류심사 및 최종발표',NULL,'~2026-04-22 오후 6시','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,can_overlap,required_documents,apply_method,apply_url,contact,note,selection_stages,selection_stage_1,selection_note,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 다문화·탈북(이주·북한배경)학생 멘토링장학금 멘토 모집','한국장학재단 / 교육부','공공기관',ARRAY['학업장려금']::support_category[],0,'2026-02-01','2027-02-28',NULL,ARRAY['재학']::enrollment_status_type[],false,ARRAY['소속 대학(원) 다문화탈북 멘토링장학금 사업 참여 및 신청절차 확인 후 신청'],'한국장학재단 홈페이지(www.kosaf.go.kr) 또는 모바일 신청','https://www.kosaf.go.kr','1599-2000 / mentoring2@kosaf.go.kr','도시 시간당 14,000원, 농어촌 18,000원 (연간 10시간 이상 활동자). 멘토링 활동기간 2026.3~2027.2. 국가근로장학금·청소년교육지원장학금과 중복 불가.',1,'대학(원)별 선발 및 최종발표','대학(원)별 일정 및 기준, 활동 시간, 운영 방법 등이 상이하므로 소속 대학(원) 공지사항 확인 필수','2026.2~2027.2 (대학별 상이)','2026-04-12',false);

-- ── 해커스 ────────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_location,qual_enrollment_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026 Hackers Bridge Scholarship (Alumni 장학생)','Hackers (해커스)','기업',ARRAY['학업장려금']::support_category[],14000000,'2026-01-01','2026-05-31','2026-06-17',2,ARRAY['해외 대학']::school_location_type[],ARRAY['재학']::enrollment_status_type[],true,ARRAY['지원서 (온라인 다운로드 후 제출)','어드미션 통지서 사본 (1차 합격자)','비자 사본 (1차 합격자)','본인명의 통장 사본 (최종합격자)'],'온라인 지원서 제출 → 1차 합격자 우편 서류 제출 → 최종합격자 추가서류 온라인 제출','https://www.hackers.com','https://www.hackers.com','scholarship@hackers.com','해커스어학원·해커스인강 수강 동문 중 2026년 해외대학(원) 어드미션 받은 자. Alumni·Family 전형 중복 지원 가능. USD 10,000 지급.',3,'서류심사(1차)','서류심사(2차)','최종발표','~2026-05-31','2026-06-10 (1차 합격자 발표) / 서류 ~2026-06-15','2026-06-17','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_location,qual_enrollment_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026 Hackers Bridge Scholarship (Family 장학생)','Hackers (해커스)','기업',ARRAY['학업장려금']::support_category[],14000000,'2026-01-01','2026-05-31','2026-06-17',2,ARRAY['해외 대학']::school_location_type[],ARRAY['재학']::enrollment_status_type[],true,ARRAY['지원서 (온라인 다운로드 후 제출)','어드미션 통지서 사본 (1차 합격자)','비자 사본 (1차 합격자)','본인명의 통장 사본 (최종합격자)'],'온라인 지원서 제출 → 1차 합격자 우편 서류 제출 → 최종합격자 추가서류 온라인 제출','https://www.hackers.com','https://www.hackers.com','scholarship@hackers.com','해커스 홈페이지 이용자 중 2026년 해외대학(원) 어드미션 받은 자. Alumni·Family 전형 중복 지원 가능. USD 10,000 지급.',3,'서류심사(1차)','서류심사(2차)','최종발표','~2026-05-31','2026-06-10 (1차 합격자 발표) / 서류 ~2026-06-15','2026-06-17','2026-04-12',false);

-- ── 국비유학생 ────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_location,qual_enrollment_status,qual_nationality,qual_military_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 국비유학생 선발시험 - 일반전형','교육부 국립국제교육원','공공기관',ARRAY['등록금','생활비']::support_category[],56000000,'2026-05-07','2026-05-20','2026-07-20',40,ARRAY['해외 대학']::school_location_type[],ARRAY['졸업']::enrollment_status_type[],'내국인','군필',false,ARRAY['응시원서','대학졸업증명서','병적증명서','성적증명서','외국어시험성적표','한국사능력검정시험성적표','국외수학계획서(자기소개서 포함)'],'한국유학종합시스템(www.studyinkorea.go.kr) 온라인 입력(5.7~5.20) → 서류 등기우편 제출','https://www.studyinkorea.go.kr','https://niied.go.kr','kscholar@korea.kr / 02-3668-1460','USD 40,000 연간 지원. 석사 최대 2년, 박사 최대 3년. 출국항공료(이코노미) 1회 지원. 중국 제외. 국내외 장학금 중복수혜 불가.',2,'서류심사(1차)','면접시험(2차)','2026-06-13 / 합격자 발표 2026-06-22','2026-07-10 / 최종발표 2026-07-20','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_location,qual_enrollment_status,qual_nationality,qual_income_level_max,qual_military_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 국비유학생 선발시험 - 꿈나래전형','교육부 국립국제교육원','공공기관',ARRAY['등록금','생활비']::support_category[],70000000,'2026-05-07','2026-05-20','2026-07-20',20,ARRAY['해외 대학']::school_location_type[],ARRAY['졸업']::enrollment_status_type[],'내국인',10,'군필',false,ARRAY['일반전형 서류 + 기준중위소득 100%이하 증빙자료','수급권자·차상위·장애인·한부모가족지원대상자 증빙자료'],'한국유학종합시스템(www.studyinkorea.go.kr) 온라인 입력(5.7~5.20) → 서류 등기우편 제출','https://www.studyinkorea.go.kr','https://niied.go.kr','kscholar@korea.kr / 02-3668-1460','저소득층 대상 우대 전형. USD 50,000 연간 지원 (일반전형보다 USD 10,000 높음). 국내외 장학금 중복수혜 불가.',2,'서류심사(1차)','면접시험(2차)','2026-06-13 / 합격자 발표 2026-06-22','2026-07-10 / 최종발표 2026-07-20','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_location,qual_enrollment_status,qual_nationality,qual_military_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 국비유학생 선발시험 - 기술·기능인전형','교육부 국립국제교육원','공공기관',ARRAY['등록금','생활비']::support_category[],56000000,'2026-05-07','2026-05-20','2026-07-20',4,ARRAY['해외 대학']::school_location_type[],ARRAY['졸업']::enrollment_status_type[],'내국인','군필',false,ARRAY['일반전형 공통서류','고등학교졸업증명서','중소기업재직경력표','재직·경력증명서'],'한국유학종합시스템(www.studyinkorea.go.kr) 온라인 입력(5.7~5.20) → 서류 등기우편 제출','https://www.studyinkorea.go.kr','https://niied.go.kr','kscholar@korea.kr / 02-3668-1460','특성화고·마이스터고 졸업 후 중소기업 재직 중인 자 (1년 이상 근무경력). USD 40,000 연간 지원.',2,'서류심사(1차)','면접시험(2차)','2026-06-13 / 합격자 발표 2026-06-22','2026-07-10 / 최종발표 2026-07-20','2026-04-12',false);

-- ── 밀알복지재단 ──────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_age_min,qual_age_max,qual_income_level_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 영케어러(가족돌봄청년) 위기극복지원사업','사회복지법인 밀알복지재단','재단법인',ARRAY['생활비']::support_category[],5000000,'2026-01-01','2026-12-31',NULL,16,24,10,false,ARRAY['사업신청서 및 정보공개동의서(사진 원본파일 첨부 필수)','소득증빙(수급자증명서·차상위증명서·건강보험료납입증명서 중 택1)','주민등록등본','주거증빙','의료증빙(장애인증명서·의료진단서·의사소견서 중 택1)'],'이메일 접수 (miral9135@miral.org)','https://www.miral.org','https://www.miral.org','miral9135@miral.org','질병 또는 장애가 있는 가족을 돌보는 만 16~24세 청년 대상. 1인 최대 500만원 (생계비·의료비·주거비 합산). 예산 소진 시 조기 종결.',1,'서류심사 및 개별 통보','2026.1~2026.12 (상시)','2026-04-12',false);

-- ── 국토교통부 ────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_age_min,qual_age_max,qual_income_level_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 국토교통부 청년월세 지원사업','국토교통부','공공기관',ARRAY['생활비']::support_category[],2400000,'2026-03-30','2026-05-29','2026-09-14',60000,19,34,10,false,ARRAY['온라인 또는 방문 신청 시 요구 서류 확인'],'온라인: 복지로 홈페이지(www.bokjiro.go.kr) / 방문: 주소지 관할 행정복지센터','https://www.bokjiro.go.kr','https://www.molit.go.kr','국토교통부 (주거복지 관련 민원)','부모님과 별도 거주하는 무주택 청년 대상. 월 최대 20만원 × 24개월. 청년독립가구 기준중위소득 60% 이하 및 원가구 100% 이하. 5월세부터 소급 지원.',1,'서류심사 및 선정자 발표','2026-05-29 접수마감 → 2026-09-14 발표','2026-04-12',false);

-- ── 풀브라이트 ────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,qual_school_location,qual_enrollment_status,qual_gpa_min,qual_nationality,qual_military_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2027 풀브라이트 대학원 장학 프로그램 (인문·사회과학·예체능)','한미교육위원단 (Fulbright Korea)','공공기관',ARRAY['등록금','생활비']::support_category[],0,'2026-04-01','2026-05-19','2026-09-18',ARRAY['해외 대학']::school_location_type[],ARRAY['졸업']::enrollment_status_type[],3.0,'내국인','군필',false,ARRAY['풀브라이트 지원서','한미교육위원단 지원서','영문 추천서 3부','TOEFL/IELTS 성적표 원본+사본','GRE/GMAT 성적표 원본+사본','영문 성적증명서','출입국사실증명서(10년치)'],'온라인: 풀브라이트·한미교육위원단 지원서 제출 (2026.4.1~5.19 오후5시) / 우편: 구비서류 등기우편 제출 (~5.19 도착분)','https://www.fulbright.or.kr','https://www.fulbright.or.kr','한미교육위원단 02-3275-4000 / application@fulbright.or.kr','미국 대학원 학비 및 생활비 전액 지원. 이공계(STEM) 제외 전 분야. TOEFL iBT 4.5점 또는 IELTS 6.5점 이상 필수. 미국 이중국적자·영주권자 불가. 장학금 수혜 개시 2027년 8~9월.',3,'서류심사','영어 면접 (일대다)','풀브라이트 해외장학이사회 최종승인','2026년 6월','2026년 7월 중순~8월 초','2026-09-18 최종발표','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,qual_school_location,qual_enrollment_status,qual_major,qual_gpa_min,qual_nationality,qual_military_status,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2027 풀브라이트 이공계 첨단분야 대학원 장학 프로그램 (STEM)','한미교육위원단 (Fulbright Korea)','공공기관',ARRAY['등록금','생활비']::support_category[],0,'2026-04-01','2026-05-19','2026-09-18',ARRAY['해외 대학']::school_location_type[],ARRAY['졸업']::enrollment_status_type[],ARRAY['이공계','바이오','반도체','AI','우주'],3.0,'내국인','군필',false,ARRAY['풀브라이트 지원서','한미교육위원단 지원서','영문 추천서 3부','TOEFL/IELTS 성적표 원본+사본','GRE/GMAT 성적표 원본+사본','영문 성적증명서'],'온라인: 풀브라이트·한미교육위원단 지원서 제출 (2026.4.1~5.19 오후5시) / 우편: 구비서류 등기우편 제출 (~5.19 도착분)','https://www.fulbright.or.kr','https://www.fulbright.or.kr','한미교육위원단 02-3275-4000 / application@fulbright.or.kr','미국 대학원 학비 및 생활비 전액 지원. 이공계(STEM) 전 분야. 첨단분야(바이오·반도체·배터리·양자·AI·우주) 지원자 우대. TOEFL iBT 4.5점 이상 필수.',3,'서류심사','영어 면접 (일대다)','풀브라이트 해외장학이사회 최종승인','2026년 6월','2026년 7월 중순~8월 초','2026-09-18 최종발표','2026-04-12',false);

-- ── 국회기후변화포럼 ──────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_enrollment_status,qual_gpa_min,qual_income_level_max,qual_special_info,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_note,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026 국회기후변화포럼 기후변화 장학생','국회기후변화포럼 / (재)문숙과학지원재단 / 한국남동발전','공공기관',ARRAY['생활비']::support_category[],4000000,'2026-03-26','2026-05-02',3,ARRAY['4년제']::school_category_type[],ARRAY['재학']::enrollment_status_type[],3.3,2,ARRAY['기초생활수급자','차상위계층']::special_info_type[],'내국인',false,ARRAY['기후변화 장학생 지원서(필수)','자기소개서(필수, 2p·11pt·휴먼명조)','개인정보수집이용동의서','성적증명서(2026년 4월 이후 발급 원본)','경제상황 증빙서류 원본 (면접 당일)'],'이메일 접수만 가능 (climateforum@climateforum.or.kr) / 우편·전화 불가. 모든 서류 하나의 PDF로 합쳐 제출','https://www.climateforum.or.kr','https://www.climateforum.or.kr','climateforum@climateforum.or.kr (평일 09:00~18:00, 전화 문의 불가)','기초생활수급자 또는 법정 차상위계층 대상. 장학금 지급 기간 2026년 7~12월. 의무사항: 기후변화 아카데미 참여, COP31 예비참관단 활동(2026.8~10). 우수학생 본참관단(2026.11.9~20, 튀르키예).',3,'서류심사 (3배수 이내)','면접심사 (대면, 서울 여의도)','최종발표','면접 당일 경제상황 증빙서류 원본 미제출 시 면접 자격 취소','~2026-05-02 접수 / 결과통보 2026-05-07','2026-05-16 (토), 서울 여의도','2026-05-19 (화)','2026-04-12',false);

-- ── 보훈 장학 ─────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,qual_school_category,qual_enrollment_status,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_note,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 1학기 보훈 장학 - 대학원 (석·박사과정)','한국보훈복지의료공단 / 국가보훈처','공공기관',ARRAY['등록금']::support_category[],2600000,'2026-04-01','2026-04-30',ARRAY['대학원']::school_category_type[],ARRAY['재학']::enrollment_status_type[],ARRAY['보훈대상자']::special_info_type[],false,ARRAY['보훈장학 신청서','개인정보이용·제공 사전동의서','재학증명서','직전학기 성적증명서(백분율 환산)','수업료 납입증명서'],'교육기관 소재지 관할 보훈(지)청 보훈과 방문 또는 등기우편 제출','https://www.bohun.or.kr','https://www.bohun.or.kr','교육기관 소재지 관할 보훈(지)청 보훈과','국가유공자 본인·배우자·자녀 등 대상. 학기당 최고 130만원 (실제 납부 수업료 이내). 선발 우선순위: ①1~7급 상이자 본인 ②비상이자 본인 ③배우자·자녀.',1,'서류심사 및 우선순위 선발','신청인원이 선발인원보다 많을 경우 우선순위 기준 선발','2026-04-01~04-30 접수 / 처리기한 30일','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,qual_school_category,qual_enrollment_status,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 1학기 보훈가족 장학 - 대학 (6·25전몰군경자녀의 자녀)','한국보훈복지의료공단 / 국가보훈처','공공기관',ARRAY['등록금']::support_category[],2000000,'2026-04-01','2026-04-30',ARRAY['4년제','전문대']::school_category_type[],ARRAY['재학']::enrollment_status_type[],ARRAY['보훈대상자']::special_info_type[],false,ARRAY['보훈가족장학 신청서','재학증명서','직전학기 성적증명서','당해학기 수업료 납입증명서','주민등록등본','장학금 신청자 통장 사본'],'교육기관 소재지 관할 보훈(지)청 보훈과 방문 또는 등기우편 제출','https://www.bohun.or.kr','https://www.bohun.or.kr','교육기관 소재지 관할 보훈(지)청 보훈과','6·25전몰군경자녀의 자녀(손자녀) 대상. 학기당 최고 100만원. 직전학기 성적 70점 이상 (신입생 제외). 선발 우선순위: ①저소득자 ②6·25전몰유자녀 미수혜 ③수혜자.',1,'서류심사 및 우선순위 선발','2026-04-01~04-30 접수','2026-04-12',false);

-- ── 인천인재평생교육진흥원 ───────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_min,qual_age_min,qual_age_max,qual_region,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026년도 인천광역시 대학생 해외연수 장학생 선발','(재)인천인재평생교육진흥원 / 인천광역시','공공기관',ARRAY['해외연수비']::support_category[],0,'2026-03-30','2026-04-15',25,ARRAY['재학','휴학']::enrollment_status_type[],3.3,19,34,ARRAY['인천광역시'],ARRAY['기초생활수급자','차상위계층','한부모가정','자립준비청년','다문화가정','보훈대상자']::special_info_type[],false,ARRAY['지원서','자기소개서','재학증명서','성적증명서','주민등록초본'],'(재)인천인재평생교육진흥원 홈페이지(www.itle.or.kr) 온라인 접수','https://www.itle.or.kr','https://www.itle.or.kr','032-722-7253 ((재)인천인재평생교육진흥원 장학사업부)','영국 셰필드대학교 어학코스 수강 및 지역 문화탐방. 연수기간: 2026.6.29~7.24. 교육비·숙박·식비·항공료·보험료 일체 지원. 인천 소재 대학 재학생은 주소지 무관 지원 가능.',3,'서류심사','면접심사','합격자 발표','2026-04-16~04-20 (면접대상자 발표 4.21)','2026-04-28 (화, 예정)','2026-04-29 오후 6시 (예정)','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_min,qual_region,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026년도 재능인 장학생','(재)인천인재평생교육진흥원','공공기관',ARRAY['학업장려금']::support_category[],2000000,'2026-04-20','2026-05-06',10,ARRAY['재학']::enrollment_status_type[],3.5,ARRAY['인천광역시'],false,ARRAY['지원신청서','자기소개서','추천서(학교장·학과장·유관단체장)','재학증명서','대회입상 확인증명서','대회수상실적서(최대 3개)'],'온라인(www.itle.or.kr)','https://www.itle.or.kr','https://www.itle.or.kr','인문사회/수학과학/문화예술/체육/기술기능 분야 전국단위 이상 대회 개인 3위·단체 1위 이내 입상자(공고일로부터 1년 이내). 대학생 5명 포함.',3,'서류심사','면접(외부심사위원)','선발심사위원회 심의','2026-04-20 ~ 2026-05-06','2026-05-07 ~ 2026-06-15 (면접 05-21 예정)','2026-06-23 예정','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_income_level_max,qual_region,qual_nationality,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 상반기 인천인희망드림 장학생','(재)인천인재평생교육진흥원','공공기관',ARRAY['학업장려금']::support_category[],1000000,'2026-03-30','2026-04-19',225,ARRAY['재학']::enrollment_status_type[],2.8,6,ARRAY['인천광역시'],'내국인',ARRAY['기초생활수급자','차상위계층','한부모가정','장애인']::special_info_type[],false,ARRAY['지원신청서','자기소개서','재학증명서','주민등록초본','성적증명서','가정형편증명서 또는 학자금 지원구간 통지서','통장사본'],'온라인(www.itle.or.kr)','https://www.itle.or.kr','https://www.itle.or.kr','가정형편 기준 우선 선발 후 성적 고득점 순. 인천 관내 대학 재학생은 거주지 무관 지원 가능.',2,'서류심사','선발심사위원회 심의','2026-03-30 ~ 2026-04-19','2026-04-20 ~ 2026-06-15','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_region,qual_nationality,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 다자녀 가정지원 장학생','(재)인천인재평생교육진흥원','공공기관',ARRAY['학업장려금']::support_category[],1000000,'2026-03-30','2026-04-19',140,ARRAY['재학']::enrollment_status_type[],2.5,ARRAY['인천광역시'],'내국인',ARRAY['다자녀']::special_info_type[],false,ARRAY['지원신청서','자기소개서','재학증명서','주민등록초본','가족관계증명서','성적증명서','통장사본'],'온라인(www.itle.or.kr)','https://www.itle.or.kr','https://www.itle.or.kr','다자녀 가정(2자녀 이상) 대상. 다자녀 순 우선 선발 후 성적 고득점 순.',2,'서류심사','선발심사위원회 심의','2026-03-30 ~ 2026-04-19','2026-04-20 ~ 2026-06-15','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_region,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 재외동포 자녀지원 장학생','(재)인천인재평생교육진흥원','공공기관',ARRAY['학업장려금']::support_category[],1000000,'2026-03-30','2026-04-19',30,ARRAY['재학']::enrollment_status_type[],2.5,ARRAY['인천광역시'],'외국인',false,ARRAY['지원신청서','자기소개서','재학증명서','외국국적동포 국내거소신고증 사본','성적증명서','통장사본'],'온라인(www.itle.or.kr)','https://www.itle.or.kr','https://www.itle.or.kr','본인 또는 부모가 재외동포 사증(F-4) 소지자. 인천 거주 또는 인천 관내 학교 재학. 성적 고득점 순 선발.',2,'서류심사','선발심사위원회 심의','2026-03-30 ~ 2026-04-19','2026-04-20 ~ 2026-06-15','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_income_level_max,qual_region,qual_nationality,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 인천대교 희망 장학생','(재)인천인재평생교육진흥원','공공기관',ARRAY['학업장려금']::support_category[],1000000,'2026-03-30','2026-04-19',30,ARRAY['재학']::enrollment_status_type[],2.5,6,ARRAY['인천광역시 중구','인천광역시 미추홀구','인천광역시 연수구'],'내국인',ARRAY['기초생활수급자','차상위계층','한부모가정','장애인']::special_info_type[],false,ARRAY['지원신청서','자기소개서','재학증명서','주민등록초본','성적증명서','가정형편증명서','통장사본'],'온라인(www.itle.or.kr)','https://www.itle.or.kr','https://www.itle.or.kr','부모 또는 본인 주민등록 주소지가 인천 중구·미추홀구·연수구. 가정형편 기준 우선 선발 후 성적 고득점 순.',2,'서류심사','선발심사위원회 심의','2026-03-30 ~ 2026-04-19','2026-04-20 ~ 2026-06-15','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_gpa_last_semester_min,qual_region,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년도 iHUG 인천도시공사 장학생','(재)인천인재평생교육진흥원','공공기관',ARRAY['학업장려금']::support_category[],1000000,'2026-03-30','2026-04-19',20,ARRAY['재학']::enrollment_status_type[],3.0,ARRAY['인천광역시'],'내국인',false,ARRAY['지원신청서','자기소개서','재학증명서','주민등록등본','가족관계증명서','인천도시공사 임대주택 계약서 사본','성적증명서','통장사본'],'온라인(www.itle.or.kr)','https://www.itle.or.kr','https://www.itle.or.kr','인천도시공사 임대주택(영구·국민임대·매입임대) 거주 가정 자녀 대상. 성적 고득점 순 선발(동점자: 세대원 많은 순).',2,'서류심사','선발심사위원회 심의','2026-03-30 ~ 2026-04-19','2026-04-20 ~ 2026-06-15','2026-04-12',false);

-- ── 옹진군 ────────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_age_max,qual_region,can_overlap,required_documents,apply_method,apply_url,contact,note,selection_stages,selection_stage_1,selection_note,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 옹진장학관 입주생 추가선발 (대학생·대학원생·취준생)','(재)옹진군인재육성재단','재단법인',ARRAY['생활비']::support_category[],0,'2026-02-04','2099-12-31',12,ARRAY['재학','휴학']::enrollment_status_type[],34,ARRAY['옹진군'],false,ARRAY['입주신청서','실거주확인서','주민등록초본','건강보험료 납부확인서','성적증명서 등'],'방문 또는 이메일 접수(ltylife9601@korea.kr) / 평일 09:00~18:00','https://www.itle.or.kr','032-899-2793~5 (옹진군청 행정자치과 인구청년팀)','수도권 소재 대학 재학생 대상. 본인 또는 부모가 옹진군에 3년 이상 연속 실거주 필수. 34세 이하. 기숙사 입주 제공 (입주일~2027.2.15.). 상시 모집.',1,'서류심사(개별통보)','상시모집·개별 심사·통보. 예비후보자 유효기간 해당연도 11월 30일까지','2026-02-04~상시','2026-04-12',false);

-- ── 수림재단 ──────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_academic_year,qual_enrollment_status,qual_major,qual_income_level_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,collected_at,is_verified)
VALUES ('2026년 수림재단 이공계 장학금','수림재단','재단법인',ARRAY['생활비']::support_category[],2400000,'2026-03-01','2026-04-30',12,ARRAY['4년제']::school_category_type[],ARRAY[2],ARRAY['재학']::enrollment_status_type[],ARRAY['자연계열','공학계열'],8,true,ARRAY['해당 대학 별도 통지 (학교장 추천 필요)'],'해당 대학 학교장 추천을 통해 지원 (각 대학에 별도 통지)','https://www.bohun.or.kr','https://www.bohun.or.kr','수림재단 (각 대학 학생처 통해 문의)','지정 15개 대학(GIST, KAIST, UNIST, 건국대, 경희대, 고려대, 동국대, 서강대, 서울대, 성균관대, 연세대, 이화여대, 중앙대, 포스텍, 한양대) 2학년 재학생 대상. 월 40만원 × 6개월 = 240만원. 학교장 추천 필수.',3,'서류심사','면접','합격자 통보','2026-04-12',false);

-- ── 백운장학회 ────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_age_max,qual_region,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 백운장학회 대학생 생활비 장학금','(재)백운장학회','재단법인',ARRAY['생활비']::support_category[],3500000,'2026-03-03','2026-04-30',NULL,ARRAY['재학']::enrollment_status_type[],34,ARRAY['광양시'],true,ARRAY['장학금 신청서(서식1)','주민등록초본 3부(본인·부·모 각 1부)','가족관계증명서 1부','재학증명서','개인정보수집이용제공동의서','통장 사본(본인 명의)','대학교 성적증명서(전체학년)'],'온라인: MY광양 앱 / 오프라인: 신청자 주소지 관할 읍·면·동사무소 또는 교육청소년과','https://www.bohun.or.kr','https://www.bohun.or.kr','교육청소년과 797-2246, 797-1954 / 각 읍면동 주민센터','학생 본인 + 부모(모두) 광양시 3년 이상 연속 거주 필수. 연 2회 신청(상반기: 3.3~4.30 / 하반기: 9.1~10.30). 지급액: 거주기간·소득구간별 100~350만원.',1,'서류심사 및 자동 지급','2026-03-03~04-30 접수 / 1개월 이내 지급','2026-04-12',false);

-- ── 논산시장학회 ──────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_age_max,qual_region,can_overlap,required_documents,apply_method,apply_url,contact,note,selection_stages,selection_stage_1,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 논산시장학회 장학금 - 학업장려 장학금 (대학 신입생)','(재)논산시장학회','재단법인',ARRAY['생활비']::support_category[],1500000,'2026-03-16','2026-04-30',NULL,NULL,22,ARRAY['논산시'],true,ARRAY['장학금 신청서·개인정보동의서','주민등록표 등본 또는 초본','통장 사본(신입생 본인 명의)','재학증명서(입학일자 기재)','고등학교 졸업증명서(2003년생)'],'방문 접수 또는 등기우편 (논산시청 인구청년교육과 교육지원팀)','https://www.itle.or.kr','논산시청 인구청년교육과 교육지원팀 041-746-5774','학생 본인·부·모 중 1명이라도 논산시에 1년 이상 거주 필수. 타 기관 장학금과 중복 가능 (논산시장학회 내부 중복 불가). 1인 1회만 지급.',1,'서류심사','2026-03-16~04-30 접수 / 5월 말 지급','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_age_max,qual_region,can_overlap,required_documents,apply_method,apply_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년 논산시장학회 장학금 - 지역대학진학 장학금 (관내 대학 신입생)','(재)논산시장학회','재단법인',ARRAY['생활비']::support_category[],2500000,'2026-03-16','2026-04-24',NULL,NULL,22,ARRAY['논산시'],true,ARRAY['장학금 신청서·개인정보동의서','주민등록표 등본 또는 초본','통장 사본(본인 명의)','재학증명서','고등학교 졸업증명서(2003년생)'],'해당 관내 대학 접수처 방문 제출 / 건양대 학생팀 041-730-5145 / 금강대 교학지원처 041-731-3213','https://www.itle.or.kr','논산시청 인구청년교육과 041-746-5774 / 각 대학 접수처','논산시 관내 대학(건양대, 금강대, 한국폴리텍대학 바이오캠퍼스) 신입생 대상. 관내 대학 학장/총장의 추천 필수. 타 기관 장학금과 중복 가능.',2,'대학 서류 검토 및 추천','장학생 선발심의·의결','2026-04-27~04-30','2026년 5월 말 지급','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_enrollment_status,qual_income_level_max,qual_region,qual_special_info,can_overlap,required_documents,apply_method,apply_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년 논산시장학회 장학금 - 사회적배려 장학금 (대학생)','(재)논산시장학회','재단법인',ARRAY['생활비']::support_category[],2000000,'2026-03-16','2026-04-30',25,ARRAY['재학']::enrollment_status_type[],8,ARRAY['논산시'],ARRAY['기초생활수급자','차상위계층','한부모가정','장애인','학생가장']::special_info_type[],true,ARRAY['장학생 추천서·개인정보동의서','주민등록표 등본 또는 초본','통장 사본(본인 명의)','재학증명서','사회적 취약계층 입증서류'],'논산시 관련 기관·부서장 추천을 통해 접수','https://www.itle.or.kr','논산시청 인구청년교육과 041-746-5774','논산시 거주자 중 사회적 취약계층 대상. 논산시 관련 기관·부서장의 추천 필수. 타 기관 장학금과 중복 가능.',2,'기관 추천','장학생 선발심의·의결','2026-03-16~04-30','2026년 5월 말 지급','2026-04-12',false);

-- ── 미래에셋박현주재단 ──────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_category,qual_enrollment_status,qual_major,qual_gpa_min,qual_income_level_max,qual_school_location,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('제35기 미래에셋 해외교환 장학생 (2026년 가을학기 파견)','미래에셋박현주재단','재단법인',ARRAY['생활비']::support_category[],8500000,'2026-04-15','2026-04-21','2026-06-25',250,ARRAY['4년제']::school_category_type[],ARRAY['재학']::enrollment_status_type[],ARRAY['이공계','상경','인문사회'],3.0,8,ARRAY['해외 대학']::school_location_type[],'내국인',false,ARRAY['지원서·자기소개서(온라인 작성)','국문 성적증명서(모교 직인, 전학년)','학자금지원구간통지서(암호해제 필수)'],'온라인 지원 전용 사이트 (미래에셋박현주재단 홈페이지 → 재단소식 → 공지사항)','https://www.miraeassetfoundation.or.kr','https://www.miraeassetfoundation.or.kr','student@miraeasset.com / 02-3774-7465 (평일 오후 2~5시)','2026년 가을학기 모교 해외교환 학생 선발(예정)자 필수. 미주·유럽 850만원 / 아시아 650만원 (한 학기 일괄 지급). 국내외 기업·재단·정부기관·국제교류프로그램 해외거주 지원 장학금과 중복 불가.',2,'서류심사 (지원자격·자기소개서·가산점)','온라인 영상면접 (서류합격자 대상)','2026-04-15~04-21 접수 / 합격자 발표 2026-05-21','2026-05-26 (온라인 영상면접) / 최종발표 2026-06-25','2026-04-12',false);

-- ── 니토리 국제장학재단 ──────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_school_location,qual_enrollment_status,qual_age_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026년도 니토리 국제장학재단 장학생 (대학생)','니토리 국제장학재단','재단법인',ARRAY['생활비']::support_category[],0,'2026-01-20','2026-04-20',350,ARRAY['4년제','대학원']::school_category_type[],ARRAY['해외 대학']::school_location_type[],ARRAY['재학']::enrollment_status_type[],25,false,ARRAY['WEB원서','WEB테스트(1차)','서류심사·온라인 면접(2차)'],'온라인(nitori-shougakuzaidan.com)','https://www.nitori-shougakuzaidan.com/application/','https://www.nitori-shougakuzaidan.com','일본 국내 4년제 대학·대학원생(일본 국적 또는 영주자·정주자) 대상. 월 5~8만엔 지급. 다른 급부형 장학금(JASSO 포함) 중복 불가.',3,'WEB원서·WEB테스트','서류심사·온라인 면접','최종발표','2026-03 하순 ~ 2026-04-20','2026-04 하순 ~ 2026-05 중순(예정)','2026-07 상순(예정)','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_school_location,qual_enrollment_status,qual_age_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026년도 니토리 국제장학재단 장학생 (유학생)','니토리 국제장학재단','재단법인',ARRAY['생활비']::support_category[],0,'2026-01-20','2026-04-20',200,ARRAY['4년제','대학원']::school_category_type[],ARRAY['해외 대학']::school_location_type[],ARRAY['재학']::enrollment_status_type[],26,false,ARRAY['WEB원서','WEB테스트(1차)','서류심사·온라인 면접(2차)'],'온라인(nitori-shougakuzaidan.com)','https://www.nitori-shougakuzaidan.com/application/','https://www.nitori-shougakuzaidan.com','일본 국내 유학(留学) 자격 사비유학생 대상. 월 6~8만엔 지급. 일본어 능력 N3 이상 필요. 다른 급부형 장학금(JASSO 포함) 중복 불가.',3,'WEB원서·WEB테스트','서류심사·온라인 면접','최종발표','2026-03 하순 ~ 2026-04-20','2026-04 하순 ~ 2026-05 중순(예정)','2026-07 상순(예정)','2026-04-12',false);

-- ── 카카오뱅크 ────────────────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_enrollment_status,qual_income_level_max,qual_nationality,can_overlap,required_documents,apply_method,apply_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026 카카오뱅크 스칼라십','유플러스핀테크 / 카카오뱅크','기업',ARRAY['생활비','학업장려금']::support_category[],3000000,'2026-03-26','2026-04-19',60,ARRAY['4년제']::school_category_type[],ARRAY['재학','졸업유예']::enrollment_status_type[],10,'내국인',true,ARRAY['지원서(온라인 서식)','자기소개서','소득 증빙서류(기준 중위소득 100% 이하 확인)','재학증명서'],'온라인(유플러스핀테크 홈페이지)','https://www.kosaf.go.kr',NULL,'재학생(2~6학기) 30명 + 졸업예정자(최종학년) 30명 구분 선발. 학기당 150만원×2=300만원. 성실참여 인센티브 월 50만원 추가(최대 3회). 오리엔테이션: 5/10(토) 또는 5/15(금) 오후 7시.',3,'서류심사','오리엔테이션(온라인)','장학금 지급 및 프로그램 시작','2026-03-26 ~ 2026-04-19','2026-05-10 또는 2026-05-15','2026-05월','2026-04-12',false);

-- ── 우리다문화장학재단 ───────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_enrollment_status,qual_income_level_max,qual_special_info,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_4,selection_stage_1_schedule,collected_at,is_verified)
VALUES ('2026년 우리다문화장학재단 장학생 - 다문화자녀 학업장학(대학)','우리다문화장학재단 (우리금융그룹)','재단법인',ARRAY['학업장려금']::support_category[],5000000,'2026-03-23','2026-04-17',60,ARRAY['4년제','전문대']::school_category_type[],ARRAY['재학','휴학']::enrollment_status_type[],10,ARRAY['다문화가정']::special_info_type[],true,ARRAY['재학증명서','장학생 추천서(지정양식·기관직인 필수)','주민등록등본','가족관계증명서','다문화 학생 입증서류','건강보험자격확인서','건강보험료 납부확인서 원본(2026년 1~3월)'],'온라인(우리다문화장학재단 홈페이지) + 원본서류 등기우편 발송(4.20 소인까지)','https://www.woorimc.or.kr','https://www.woorimc.or.kr','02-2125-2120~2124','다문화가족 자녀 대상. 장학금 500만원을 체크카드 포인트 2회 분할지급(7월/10월). 대학 장학생 서포터즈 우리누리 활동 필수(5~12월). 우리다문화장학재단 내 타 전형과 중복지원 불가.',4,'적격평가(지원자격·서류제출 확인)','서류평가','역량평가(자기소개서·추천서)','인터뷰(필요시)','2026-03-23 ~ 2026-04-17 (17:00 마감)','2026-04-12',false);

-- ── 한국예술인복지재단 ──────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_age_min,qual_income_level_max,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년 예술활동준비금 지원사업','한국예술인복지재단','공공기관',ARRAY['학업장려금']::support_category[],3000000,'2026-03-23','2026-04-17',18333,19,10,false,ARRAY['온라인 신청서(동의서 3종·확인서 2종 포함)','주민등록초본(해당자)','출입국사실증명(재외국민)'],'온라인(www.kawfartist.net) / 불가피한 경우 우편 1회 한정 (3.23~4.3 소인)','https://www.kawfartist.net','https://www.kawfartist.kr','02-3668-0200 (콜센터)','예술인 복지법상 예술활동증명 완료자 대상. 1인 300만원, 6월부터 순차 지급. 장애예술인 우선 선정. 성희롱·성폭력 예방교육 이수 필수.',2,'서류검토·전문심의','결과발표','2026-03-23 ~ 2026-04-17 (17:00 마감)','2026-05 말 예정','2026-04-12',false);

-- ── 달서인재육성장학재단 ────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_category,qual_enrollment_status,qual_region,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년 달서인재육성장학재단 진학장학생','(재)달서인재육성장학재단','재단법인',ARRAY['등록금']::support_category[],2300000,'2026-03-16','2026-04-16','2026-05-01',30,ARRAY['4년제']::school_category_type[],NULL,ARRAY['대구광역시 달서구'],'내국인',true,ARRAY['진학 장학생 신청 및 추천서(별지 제1호)','품행 및 장학금 수혜여부 확인서(별지 제2호)','개인정보 동의서','성적증명서(내신: 고2·3학년, 수능: 수능성적증명서)','주민등록초본(최근 5년 이상)','통장사본'],'방문 또는 우편(마감일 소인까지)','https://www.dalseoij.org','https://www.dalseoij.org','(053)667-3232','대구 달서구 관내 거주 구민 또는 그 자녀 대상. 내신우수(40% 이상 1등급)·수능우수(국수영 등급합 7 이내) 각 15명. 타 장학금 중복수혜 가능. 장학금 수여식 참여 필수(2026.5.8 예정).',2,'서류심사','최종발표','2026-03-16 ~ 2026-04-16 (18:00)','2026-05-01 예정','2026-04-12',false);

-- ── 한국건설기술인협회 ──────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_enrollment_status,qual_major,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_1_schedule,selection_stage_2_schedule,collected_at,is_verified)
VALUES ('2026년 예비 건설엔지니어 장학금 (한국건설기술인협회)','한국건설기술인협회','공공기관',ARRAY['학업장려금']::support_category[],1000000,'2026-03-16','2026-04-17',110,ARRAY['4년제','전문대']::school_category_type[],ARRAY['재학']::enrollment_status_type[],ARRAY['건설기술관련 학과','건축학과','건축공학과','토목공학과','기계공학과'],true,ARRAY['추천서 및 자기소개서(협회서식·학과장 직인)','동의서(협회서식)','한국장학재단 소득분위 통지서(2026년 1학기)','성적증명서'],'한국건설기술인협회 홈페이지 또는 우편(마감일 소인까지)','https://www.kocea.or.kr','https://www.kocea.or.kr','02-3416-9371 (회원복지팀)','건설기술관련 학과 재학생 대상. 부문: ①건설산업재해 피해자녀 20명 ②건설기술인(협회 정회원) 자녀 90명. 소속 학과장 추천 필수(학과별 2인 이내). 소득분위 낮은 순 우선 선발.',2,'서류심사','최종발표','2026-03-16 ~ 2026-04-17 (24:00)','2026-05 중순 이후','2026-04-12',false);

-- ── 현대차 정몽구 재단 ───────────────────────────────────────

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,selection_count,qual_school_category,qual_academic_year,qual_enrollment_status,qual_major,qual_income_level_max,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026 현대차 정몽구 스칼러십 - 과학기술 스칼러십','현대차 정몽구 재단','재단법인',ARRAY['생활비','학업장려금','해외연수비']::support_category[],12000000,'2026-03-25','2026-04-15',NULL,ARRAY['4년제']::school_category_type[],ARRAY[2,3],ARRAY['재학']::enrollment_status_type[],ARRAY['이공계 전 분야'],10,'내국인',false,ARRAY['온라인 지원서','성적증명서','재학증명서','소득 관련 서류'],'온라인(cmkfoundation-scholarship.org)','https://cmkfoundation-scholarship.org','https://cmkfoundation-scholarship.org','02-6958-1947 (과학기술 스칼러십 운영사무국)','학습장학금 600만원/학기(정규학기 이내). 국제 학술대회 장학금(연 1회, 최대 300만원). 글로벌 우수 장학금(연 최대 1,000만원 미만). 홈스쿨링 장학금 300~600만원/학기. 가구 중위소득 150% 이하. 백분위 90점 이상.',3,'서류심사','전공면접','인성면접','~2026-04-15 (15시)','2026-05-12 ~ 2026-05-14','2026-06-09 ~ 2026-06-10','2026-04-12',false);

INSERT INTO public.scholarships (name,organization,institution_type,support_types,support_amount,apply_start_date,apply_end_date,announcement_date,selection_count,qual_school_category,qual_academic_year,qual_enrollment_status,qual_major,qual_income_level_max,qual_nationality,can_overlap,required_documents,apply_method,apply_url,homepage_url,contact,note,selection_stages,selection_stage_1,selection_stage_2,selection_stage_3,selection_stage_1_schedule,selection_stage_2_schedule,selection_stage_3_schedule,collected_at,is_verified)
VALUES ('2026 현대차 정몽구 스칼러십 - 문화예술 스칼러십 (대학생)','현대차 정몽구 재단','재단법인',ARRAY['생활비','학업장려금','해외연수비']::support_category[],12000000,'2026-03-25','2026-04-15','2026-06-01',20,ARRAY['4년제']::school_category_type[],ARRAY[1,2,3],ARRAY['재학']::enrollment_status_type[],ARRAY['피아노','성악','관악(목관·금관)','현악','발레'],10,'내국인',false,ARRAY['온라인 지원서','서류/영상심사 자료','재학증명서','소득 관련 서류'],'온라인(cmkfoundation-scholarship.org)','https://cmkfoundation-scholarship.org','https://cmkfoundation-scholarship.org','02-780-5054 (문화예술 스칼러십 운영사무국)','학습장학금 600만원/학기. 국제 콩쿠르 장학금(연 1회, 최대 500만원). 글로벌 우수 장학금(입상 시 300만원). 홈스쿨링 장학금 300~600만원/학기. 가구 중위소득 150% 이하.',3,'서류·영상심사','실기심사','최종발표','~2026-04-15 (15시)','2026-04-16 ~ 2026-04-24','2026-05-18 ~ 2026-05-22','2026-04-12',false);

COMMIT;
