/**
 * 상세 페이지·탭에 필요한 scholarships 컬럼만 조회한다 (select("*") 대체).
 * ScholarshipTabs ScholarshipDetail + 페이지 히어로/혜택 필드와 동기화할 것.
 */
export const SCHOLARSHIP_DETAIL_SELECT = [
  "id",
  "name",
  "organization",
  "institution_type",
  "apply_url",
  "homepage_url",
  "support_types",
  "support_amount_text",
  "apply_start_date",
  "apply_end_date",
  "selection_count",
  "announcement_date",
  "can_overlap",
  "qual_gpa_min",
  "qual_gpa_last_semester_min",
  "qual_last_semester_earned_credits_min",
  "qual_income_level_max",
  "qual_income_level_min",
  "qual_household_size_max",
  "qual_gender",
  "qual_age_min",
  "qual_age_max",
  "qual_region",
  "qual_major",
  "qual_special_info",
  "qual_extra_requirements",
  "qual_parent_occupation",
  "qual_military_status",
  "qual_nationality",
  "qual_admission_type",
  "qual_parent_cohabitation",
  "qual_parent_region",
  "qual_university",
  "qual_enrollment_status",
  "qual_school_location",
  "qual_school_category",
  "qual_academic_year",
  "apply_method",
  "required_documents",
  "contact",
  "selection_note",
  "original_notice_image_url",
  "original_notice_image_urls",
  "original_notice_text",
  "note",
  "is_advertisement",
  "ad_job_role",
  "ad_required_skills",
  "ad_location",
  "poster_image_url",
  "view_count",
].join(", ");

/** 공모전/교육/활동 상세에 필요한 contests 컬럼 */
export const CONTEST_DETAIL_SELECT = [
  "id",
  "name",
  "organization",
  "organization_type",
  "content_kind",
  "apply_url",
  "homepage_url",
  "support_amount_text",
  "apply_start_date",
  "apply_end_date",
  "selection_count",
  "announcement_date",
  "apply_method",
  "required_documents",
  "document_files",
  "contact",
  "selection_note",
  "original_notice_image_url",
  "original_notice_image_urls",
  "original_notice_text",
  "note",
  "poster_image_url",
  "view_count",
  "interest_categories",
  "is_verified",
].join(", ");
