/**
 * 보유 스킬 택소노미 (그룹바이 techStacks 기반).
 * - profiles.skills: 프로필 보유 스킬
 * - profile_spec_items.skills: 경험에서 사용한 스킬
 */

export const SKILL_MAX = 20;
/** 경험 항목당 사용 스킬 최대 개수 */
export const EXPERIENCE_SKILL_MAX = 15;

export const SKILL_CATALOG = [
  "C",
  "C++",
  "C#",
  "Java",
  "JavaScript",
  "TypeScript",
  "Python",
  "Swift",
  "Perl",
  "Ruby",
  "PHP",
  "R",
  "Scala",
  "Rust",
  "Kotlin",
  "Go",
  "Objective-C",
  "AngularJS",
  "BackboneJS",
  "Electron",
  "Emotion",
  "Gatsby",
  "GraphQL",
  "Immer",
  "MobX",
  "NextJS",
  "NuxtJS",
  "OpenGL",
  "React-Context",
  "ReactiveX",
  "ReactJS",
  "Redux",
  "Recoil",
  "Storybook",
  "Svelte",
  "Tailwind",
  "Unity",
  "VueJS",
  "Vuex",
  "Apache",
  "NGINX",
  "Google-Web-Server",
  "Apollo",
  "Armeria",
  "ASP.NET",
  "AWS-Kinesis",
  "AWS-SES",
  "AWS-SNS",
  "AWS-SQS",
  "Celery",
  "Django",
  "ExpressJS",
  "FastAPI",
  "Fastify",
  "Flask",
  "GRPC",
  "Hibernate",
  "Koa",
  "Laravel",
  "Liquibase",
  "MyBatis",
  "NestJS",
  "Netty",
  "NodeJS",
  "RabbitMQ",
  "Relay",
  "Ruby-on-Rails",
  "Spring",
  "SpringBoot",
  "Swagger",
  "Thrift",
  "Arcus",
  "AWS-AuroraDB",
  "AWS-DocumentDB",
  "AWS-DynamoDB",
  "AWS-MariaDB",
  "CassandraDB",
  "Ceph",
  "CockroachDB",
  "Couchbase",
  "Cubrid",
  "ElasticSearch",
  "Greenplum",
  "InfluxDB",
  "Memcached",
  "MongoDB",
  "MSSQL",
  "MySQL",
  "Neo4j",
  "OracleDB",
  "PostgreSQL",
  "Redis",
  "RocksDB",
  "Solr",
  "Airflow",
  "AWS-Athena",
  "AWS-Redshift",
  "Clickhouse",
  "Druid",
  "Flink",
  "Fluentd",
  "Google-BigQuery",
  "Google-Data-Studio",
  "Grafana",
  "Hadoop",
  "HBase",
  "Hive",
  "Impala",
  "Kafka",
  "Keras",
  "Kibana",
  "Kubeflow",
  "Kuda",
  "Looker",
  "Luigi",
  "Metabase",
  "MLflow",
  "NIFI",
  "Presto",
  "Prometheus",
  "Pytorch",
  "Ray",
  "Redash",
  "Spark",
  "Superset",
  "Tableau",
  "Tensorflow",
  "Zeppelin",
  "Zipkin",
  "Alamofire",
  "Bazel",
  "Dagger",
  "ExoPlayer",
  "Fastlane",
  "Flutter",
  "Glide",
  "Google-Firebase",
  "Google-Firestore",
  "Lottie",
  "React-Native",
  "ReactorKit",
  "Realm",
  "Retrofit",
  "RIBs",
  "SnapKit",
  "Unreal",
  "DirectX",
  "PhysX",
  "Bullet",
  "Ansible",
  "Argo-CD",
  "AWS-CodeBuild",
  "AWS-CodePipeline",
  "Azure-DevOps",
  "Bitbucket",
  "Bitrise",
  "Capistrano",
  "Central-Dogma",
  "Circle-CI",
  "Docker",
  "Drone",
  "Github",
  "Github-Action",
  "Gitlab-CI",
  "Go-CD",
  "Google-Cloud-Build",
  "Gulp",
  "Harbor",
  "Helm",
  "Jaeger",
  "Jenkins",
  "Kube-Bench",
  "Kubernetes",
  "OpenEBS",
  "Packer",
  "Rundeck",
  "Saltstack",
  "Spinnaker",
  "Terraform",
  "Traefik",
  "Travis-CI",
  "Zabbix",
  "HTML/CSS",
  "RESTful API",
  "Jira",
  "SCSS",
  "SASS",
  "Android",
  "RxSwift",
  "iOS",
  "Firebase",
  "MariaDB",
  "AWS",
  "AWS-RDS",
  "Git",
  "GitLab",
  "AWS-EC2",
  "AWS-S3",
  "AWS-Route53",
  "Human Tracking",
  "Pose Estimation",
  "Object Detection",
  "Multi-object Tracking",
  "Gstreamer",
  "NNStreamer",
  "Notion",
  "Figma",
  "Jandi",
  "NCP",
  "NoSQL",
  "Sentry",
  "RxJS",
  "ES6",
  "Shell Scripting",
  "AWE",
  "AWS-ECS",
  "Logstash",
  "Fargate",
  "CloudWatch",
  "SQL",
  "SqlAlchemy",
  "Reactive",
  "3D Rendering",
  "AWS-ECR",
  "Jupyter",
  "Tornado",
  "NLP",
  "JSP",
  "AWS-EBS",
  "Docker Compose",
  "AWS-ELB",
  "Sagemaker",
  "Styled-Component",
  "New Relic",
  "Azure-Blob Storage",
  "WebGL",
  "Three.js",
  "Paper.js",
  "Webpack",
  "Babel",
  "Jest",
  "Tibero",
  "Alembic",
  "Structlog",
  "Click",
  "Pytest",
  "React-Query",
  "Vercel",
  "CloudFront",
  "Vite",
  "Linux",
  "AWS-CDK",
  "SAM",
  "Elastic",
  "AWS-Lambda",
  "Ubuntu",
  "Zustand",
  "Radash",
  "Unocss",
  "Ajv",
  "Sketch",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Xd",
  "Blender",
  "Framer",
  "ProtoPie",
  "Adobe InDesign",
  "Adobe After Effects",
  "Adobe Premiere Pro",
  "Mailchimp",
  "Stibee",
  "Salesforce",
  "HubSpot",
  "Nate",
  "Kakao",
  "Tiktok",
  "Linkedin",
  "Meta",
  "Youtube",
  "Google Ads (SA,DA,App, Video)",
  "Naver (SA,DA,shopping)",
  "Microsoft Word",
  "Microsoft Excel",
  "PowerPoint",
  "Power BI",
  "FineReport",
  "BigQuery",
  "Looker Studio",
  "Appsflyer",
  "Airbridge",
  "Hotjar",
  "GTM",
  "Braze",
  "Amplitude",
  "Branch",
  "GA4",
  "3dsMax",
  "Maya",
  "Final Cut Pro",
  "Dart",
  "GetX",
  "Provide",
  "JQuery",
  "PixiJS",
  "RocketMQ",
  "Stable Diffusion",
  "Midjourney",
  "DALL·E",
  "KingFisher",
  "MapKit",
  "UIView Animation",
  "Confluence",
  "Capture One",
  "Adobe Lightroom",
  "Rhino",
  "KeyShot",
  "CAD",
  "MVVM",
  "LiveData",
  "coroutines",
  "Webview",
  "Room",
  "ViewModel",
  "ViewBinding",
  "DataStore",
  "Hilt",
  "Retrofit2",
  "Jetpack",
  "Compose",
  "Dio",
  "Socket.IO",
  "CPA",
  "CVR",
  "Zapier",
  "Mixpanel",
  "Prompt",
  "FLUX",
  "Cisco",
  "Okta",
  "Slack",
  "SSO",
  "ActiveDirectory",
  "ActiveDirectoryCertificateServices",
  "NGFW",
  "SSL",
  "Google-Cloud-Platform",
  "SAP",
  "MCU",
  "FreeRTOS",
  "LVGL",
  "Google Display & Video 360",
  "더존 Smart A",
  "더존 WEHAGO",
  "더존 iCUBE",
  "세무사랑",
  "영림원",
  "Creatie",
  "Qt creator",
  "Altium",
  "STM32WB",
  "GUI",
  "Axure",
  "DaVinci Resolve",
  "Solidity",
  "SpringDataJPA",
  "ABAP",
  "TensorBoard",
  "iBATIS",
  "Nexacro",
  "Jotai",
  "Allo",
  "Loki",
  "Tempo",
  "Vulkan",
  "Matlab",
  "Cinema 4D",
  "Octane Renderer",
  "Redshift Renderer",
  "AWS-CodeArtifact",
  "Webflow",
  "Spline",
  "MSA",
  "Vegas Pro",
  "ZBrush",
  "Substance Painter",
  "Nuke",
  "Mari",
  "Relate",
  "Mixmax",
  "Altibase",
  "SVN",
  ".Net",
  "QueryDSL",
  "SPSS",
  "D3.js",
  "OpenSearch",
  "Lucene",
  "Classic ASP",
  "Spine2D",
  "Cocos Studio",
  "AWS-EKS",
  "AWS-EB",
  "Adobe Animate",
  "CUDA",
  "AutoCAD",
  "Creo",
  "UG/NX",
  "SolidWorks",
  "FlexSim",
  "ExtendSim",
  "Phase",
  "Maze",
  "PCB-Artwork",
  "CATIA",
  "Make",
  "MS Power Automate",
  "JUnit",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "Vert.x",
  "Docker Swarm",
  "Stomp.js",
  "Lua",
  "Embedded Linux",
  "Computer Vision",
  "Datadog",
  "AWX",
  "AWS-bedrock",
  "Prettier",
  "ESLint",
  "TanStackRouter",
  "RadixUI",
  "Postman",
  "Revit",
  "Sketchup",
  "ROS",
  "DSPy",
  "QGIS",
  "GDAL",
  "Supabase",
  "OpenStack",
  "Adobe XD",
  "Google Apps Script",
  "Verilog",
  "CLO 3D",
  "ArcGIS",
  "Mantis",
  "Streamlit",
  "CodeIgniter",
  "Phalcon",
  "WPF",
  "Amaranth 10",
  "ARCore",
  "ARKit",
  "ARFoundation",
  "Spring Batch",
  "Adobe Analytics",
  "Enscape",
  "Prisma",
  "V-Ray",
  "WebRTC",
  "WordPress",
  "Ktor",
  "Clipstudio",
  "JDBC",
  "SwiftUI",
  ".NET MAUI",
  "jOOQ",
  "Spring AI",
  "dbt",
  "TypeORM",
  "Appium",
  "Selenium",
  "Spring Cloud Gateway",
  "XGBoost",
  "LightGBM",
  "Optuna",
  "Hyperopt",
  "Ansys",
  "Abaqus",
  "HWP",
  "N8N",
  "Arduino",
  "Swift Concurrency",
  "Combine",
  "TCA",
  "Clarity",
  "CapCut",
  "Cypress",
  "Delphi",
  "Apache Iceberg",
  "BullMQ",
  "MoEngage",
  "Snowflake",
  "UIKit",
  "OpenCV",
  "Fusion360",
  "Inventor",
  "ScreamingFrog",
  "Semrush",
  "Ahrefs",
  "Aspen Plus",
  "gPROMS",
  "DWSIM",
  "Keycloak",
  "OpenLayers",
  "LabVIEW",
  "ComfyUI",
  "Wireshark",
  "IDS",
  "IPS",
  "Auth.js",
  "ChatGPT",
  "Codex",
  "Claude",
  "Claude Code",
  "Gemini",
  "Grok",
  "Perplexity",
  "Runway",
  "Higgsfield",
  "Canva",
  "OpenClaw",
  "Hermes Agent",
  "Lovable",
  "Manus",
  "Databricks",
  "Groovy",
  "GSAP",
  "Linear",
  "NUnit",
  "SonarQube",
  "Splunk",
  "UWP",
  "CLOVA X",
  "뤼튼",
  "Meta AI",
  "Le Chat",
  "DeepSeek",
  "Qwen",
  "Poe",
  "GitHub Copilot",
  "Cursor",
  "Windsurf",
  "Cline",
  "Replit AI",
  "Vercel v0",
  "Bolt",
  "Tabnine",
  "Codeium",
  "Aider",
  "Devin",
  "Supermaven",
  "Zapier AI",
  "LlamaIndex",
  "CrewAI",
  "AutoGen",
  "Assistants API",
  "Dify",
  "Flowise",
  "Voiceflow",
  "Botpress",
  "Stack AI",
  "Genspark",
  "DALL·E 3",
  "Adobe Firefly",
  "Ideogram",
  "Leonardo AI",
  "Canva AI",
  "Playground AI",
  "Recraft",
  "Krea AI",
  "Sora",
  "Kling AI",
  "HeyGen",
  "Synthesia",
  "Descript",
  "Captions",
  "Pika",
  "CapCut AI",
  "Luma AI",
  "Veed.io",
  "Topaz Video AI",
  "ElevenLabs",
  "Whisper",
  "CLOVA Note",
  "Otter.ai",
  "Fathom",
  "Fireflies.ai",
  "Krisp",
  "Suno",
  "Udio",
  "Adobe Podcast",
  "Murf AI",
  "Riverside",
  "Notion AI",
  "Gamma",
  "Beautiful.ai",
  "Tome",
  "Napkin AI",
  "Julius AI",
  "ChatPDF",
  "Humata",
  "Microsoft Copilot",
  "Google Workspace AI",
  "Grammarly AI",
  "Jasper",
  "Copy.ai",
  "Wordtune",
  "Mem",
  "Elicit",
  "Consensus",
  "Semantic Scholar",
  "Connected Papers",
  "Scite",
  "ChatGPT Browse",
  "STORM",
  "Figma AI",
  "Uizard",
  "Galileo AI",
  "Locofy",
  "Framer AI",
  "Relume",
  "Webflow AI",
  "Code Interpreter",
  "Noteable",
  "Tableau AI",
  "Power BI Copilot",
  "ThoughtSpot",
  "Obviously AI",
  "DataRobot",
  "OpenAI",
  "Anthropic API",
  "Google AI Studio",
  "Hugging Face",
  "Pinecone",
  "Weaviate",
  "Chroma",
  "Qdrant",
  "Langfuse",
  "W&B",
  "CLOVA Studio",
  "Together AI",
  "Groq",
  "Replicate",
  "Modal",
  "Ollama",
  "Persado",
  "Smartly.io",
  "Gong",
  "Chorus",
  "Clay",
  "Instantly AI",
  "Lavender",
  "Brand24",
  "Surfer SEO",
  "Semrush AI",
  "HireVue",
  "Pymetrics",
  "Fetcher",
  "Beamery",
  "SeekOut",
  "Eightfold AI",
  "Lex",
  "Lobe Chat",
  "Character.AI",
  "Pi",
  "Cody",
  "Whimsical AI",
  "Loom AI",
  "LangGraph",
  "Google Cloud Speech-to-Text API",
  "GPT",
  "Automotive SPICE",
  "ISO 26262",
  "AUTOSAR",
  "CANoe",
  "CAN",
  "CAPL",
  "RTOS",
  "UART",
  "STM32",
  "Renesas",
  "Simulink",
  "SLAM",
  "ROS 2",
  "TRACE32",
  "OTA",
  "SQLite",
  "IoT",
  "DBeaver",
  "OrCAD",
  "PSpice",
  "MFC",
  "WinForms",
  "OutSystems",
  "FAISS",
  "CSMS",
  "Adobe Dimension",
  "Playwright"
] as const;

export type SkillName = (typeof SKILL_CATALOG)[number];

const SKILL_SET = new Set<string>(SKILL_CATALOG);

export function isSkillName(value: string): value is SkillName {
  return SKILL_SET.has(value);
}

export function normalizeSkills(
  raw: string[] | null | undefined,
  max = SKILL_MAX
): SkillName[] {
  if (!raw || raw.length === 0) return [];
  const out: SkillName[] = [];
  const seen = new Set<string>();
  for (const item of raw) {
    const name = String(item ?? "").trim();
    if (!name || seen.has(name) || !isSkillName(name)) continue;
    seen.add(name);
    out.push(name);
    if (out.length >= max) break;
  }
  return out;
}
