-- Contests as a separate content type from scholarships.
-- No scholarship qual_* fields. Interest taxonomy IDs shared with profiles
-- (lib/interestCategories.ts).

-- ── Published contests ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.contests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name text NOT NULL,
  organization text NOT NULL,
  organization_type text NULL,

  -- 시상 규모 등 (장학금 support_amount_text에 대응)
  support_amount_text text NULL,
  selection_count integer NULL,

  apply_start_date date NULL,
  apply_end_date date NULL,
  announcement_date date NULL,

  -- 공모전 메타 (장학금 자격요건이 아님)
  targets text[] NULL,          -- 참가 대상 (대학생, 제한없음 등)
  benefits text[] NULL,         -- 활동 혜택
  apply_types text[] NULL,      -- 접수 방식 라벨

  -- Career GPS 관심분야 태그 (고정 id). 공고는 프로필 max(5)와 달리 복수 허용.
  interest_categories text[] NULL,

  required_documents text[] NOT NULL DEFAULT '{}'::text[],
  apply_method text NOT NULL DEFAULT '',
  apply_url text NOT NULL DEFAULT '',
  homepage_url text NULL,
  contact text NULL,
  note text NULL,
  selection_note text NULL,

  poster_image_url text NULL,
  original_notice_image_url text NULL,
  original_notice_image_urls text[] NULL,
  original_notice_text text NULL,

  -- 출처 (예: linkareer)
  source text NULL,
  external_id text NULL,
  source_url text NULL,

  view_count integer NOT NULL DEFAULT 0,
  is_verified boolean NOT NULL DEFAULT false,
  list_on_home boolean NOT NULL DEFAULT true,
  is_recommended boolean NOT NULL DEFAULT false,
  recommended_sort_order integer NULL,

  collected_at date NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT contests_interest_categories_valid CHECK (
    interest_categories IS NULL
    OR (
      interest_categories <@ ARRAY[
        'planning',
        'dev',
        'data_ai',
        'design',
        'content',
        'marketing',
        'business',
        'engineering',
        'humanities',
        'education',
        'public',
        'startup'
      ]::text[]
    )
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS contests_source_external_id_uidx
  ON public.contests (source, external_id)
  WHERE source IS NOT NULL AND external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS contests_apply_end_date_idx
  ON public.contests (apply_end_date DESC);

CREATE INDEX IF NOT EXISTS contests_list_on_home_verified_idx
  ON public.contests (list_on_home, is_verified, apply_end_date DESC);

CREATE INDEX IF NOT EXISTS contests_interest_categories_gin
  ON public.contests USING gin (interest_categories);

DROP TRIGGER IF EXISTS contests_set_updated_at ON public.contests;
CREATE TRIGGER contests_set_updated_at
  BEFORE UPDATE ON public.contests
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.contests IS
  'Career GPS contests (separate from scholarships). No qual_* matching fields; uses interest_categories.';
COMMENT ON COLUMN public.contests.interest_categories IS
  'Interest taxonomy IDs from lib/interestCategories.ts (planning, dev, …).';
COMMENT ON COLUMN public.contests.support_amount_text IS
  'Award/prize scale text (e.g. 2300만원).';

-- ── Contest selection / schedule stages ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.contest_selection_stages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contest_id bigint NOT NULL REFERENCES public.contests (id) ON DELETE CASCADE,
  stage_order integer NOT NULL,
  title text NOT NULL,
  phase text NOT NULL DEFAULT 'selection'
    CHECK (phase IN ('selection', 'post_acceptance')),
  schedule_date date NULL,
  schedule_text text NULL,
  note text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contest_selection_stages_contest_id_idx
  ON public.contest_selection_stages (contest_id, stage_order);

DROP TRIGGER IF EXISTS contest_selection_stages_set_updated_at ON public.contest_selection_stages;
CREATE TRIGGER contest_selection_stages_set_updated_at
  BEFORE UPDATE ON public.contest_selection_stages
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ── Crawl / review staging (Linkareer 등) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crawled_contests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_group text NOT NULL DEFAULT 'linkareer',
  source_id text NOT NULL,
  source_name text NOT NULL DEFAULT 'linkareer',
  title text NOT NULL,
  notice_url text NOT NULL,
  notice_posted_at date NULL,
  raw_date_text text NULL,
  body text NULL,
  image_urls text[] NULL,
  poster_image_url text NULL,
  status text NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'promoted', 'rejected')),
  contest_id bigint NULL REFERENCES public.contests (id) ON DELETE SET NULL,
  extracted_draft jsonb NULL,
  reviewed_at timestamptz NULL,
  reviewed_by uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  review_note text NULL,
  run_at timestamptz NULL,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT crawled_contests_source_uidx UNIQUE (source_group, source_id)
);

CREATE INDEX IF NOT EXISTS crawled_contests_status_idx
  ON public.crawled_contests (status, last_seen_at DESC);

DROP TRIGGER IF EXISTS crawled_contests_set_updated_at ON public.crawled_contests;
CREATE TRIGGER crawled_contests_set_updated_at
  BEFORE UPDATE ON public.crawled_contests
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

COMMENT ON TABLE public.crawled_contests IS
  'Staging table for contest crawls (e.g. Linkareer) before admin promote to contests.';

-- ── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.contests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contest_selection_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crawled_contests ENABLE ROW LEVEL SECURITY;

-- contests: public read verified; admin full CRUD
DROP POLICY IF EXISTS contests_public_read ON public.contests;
CREATE POLICY contests_public_read
  ON public.contests FOR SELECT
  USING (is_verified = true);

DROP POLICY IF EXISTS "Admin users can read all contests" ON public.contests;
CREATE POLICY "Admin users can read all contests"
  ON public.contests FOR SELECT
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admin users can insert contests" ON public.contests;
CREATE POLICY "Admin users can insert contests"
  ON public.contests FOR INSERT
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin users can update contests" ON public.contests;
CREATE POLICY "Admin users can update contests"
  ON public.contests FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin users can delete contests" ON public.contests;
CREATE POLICY "Admin users can delete contests"
  ON public.contests FOR DELETE
  USING (public.is_admin());

-- contest_selection_stages: readable when parent contest is verified (or admin)
DROP POLICY IF EXISTS contest_stages_public_read ON public.contest_selection_stages;
CREATE POLICY contest_stages_public_read
  ON public.contest_selection_stages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.contests c
      WHERE c.id = contest_id AND c.is_verified = true
    )
    OR public.is_admin()
  );

DROP POLICY IF EXISTS "Admin users can insert contest stages" ON public.contest_selection_stages;
CREATE POLICY "Admin users can insert contest stages"
  ON public.contest_selection_stages FOR INSERT
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin users can update contest stages" ON public.contest_selection_stages;
CREATE POLICY "Admin users can update contest stages"
  ON public.contest_selection_stages FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin users can delete contest stages" ON public.contest_selection_stages;
CREATE POLICY "Admin users can delete contest stages"
  ON public.contest_selection_stages FOR DELETE
  USING (public.is_admin());

-- crawled_contests: admin only
DROP POLICY IF EXISTS "Admin users can read crawled contests" ON public.crawled_contests;
CREATE POLICY "Admin users can read crawled contests"
  ON public.crawled_contests FOR SELECT
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admin users can insert crawled contests" ON public.crawled_contests;
CREATE POLICY "Admin users can insert crawled contests"
  ON public.crawled_contests FOR INSERT
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin users can update crawled contests" ON public.crawled_contests;
CREATE POLICY "Admin users can update crawled contests"
  ON public.crawled_contests FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin users can delete crawled contests" ON public.crawled_contests;
CREATE POLICY "Admin users can delete crawled contests"
  ON public.crawled_contests FOR DELETE
  USING (public.is_admin());
