-- 2026 재능 Dream 희망 장학금
-- 원문 지원유형 '장학금'은 스키마 enum 호환을 위해 '학업장려금'으로 저장

INSERT INTO public.scholarships (
  name,
  organization,
  institution_type,
  support_types,
  support_amount_text,
  apply_start_date,
  apply_end_date,
  announcement_date,
  selection_count,
  qual_university,
  qual_school_location,
  qual_school_category,
  qual_academic_year,
  qual_enrollment_status,
  qual_major,
  qual_region,
  qual_nationality,
  qual_special_info,
  can_overlap,
  required_documents,
  apply_method,
  apply_url,
  homepage_url,
  contact,
  note,
  selection_stages,
  selection_stage_1,
  selection_stage_1_schedule,
  selection_stage_2,
  selection_stage_2_schedule,
  selection_stage_3,
  selection_stage_3_schedule,
  selection_stage_4,
  selection_stage_4_schedule,
  selection_note,
  collected_at,
  is_verified,
  list_on_home,
  is_recommended
)
SELECT
  '2026 재능 Dream 희망 장학금',
  '한국지역난방공사, 굿네이버스',
  '공공기관',
  ARRAY['학업장려금']::support_category[],
  '1인당 장학금 250만원 (교육봉사활동 인증에 따라 2회 분할지급)',
  DATE '2026-05-13',
  DATE '2026-06-11',
  DATE '2026-06-26',
  43,
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY['재학']::enrollment_status_type[],
  NULL,
  ARRAY['서울', '경기', '대구', '김해', '양산']::text[],
  '내국인',
  ARRAY['잔여 학기가 정규 1개 학기 이상인 자', '에너지, 환경 관련 전공 우대']::text[],
  true,
  ARRAY['장학금 지원 신청서']::text[],
  '이메일 제출 (hkim4@gni.kr)',
  'mailto:hkim4@gni.kr',
  NULL,
  '02-6424-1687 / hkim4@gni.kr',
  E'교육봉사활동 65시간 이수 필수. 2026년 2학기 휴학/자퇴 예정자 신청 불가.',
  4,
  '서류접수',
  '2026-05-13 ~ 2026-06-11',
  '서류합격자발표',
  '2026-06-17',
  '면접',
  '2026-06-23 ~ 2026-06-24',
  '최종합격자발표',
  '2026-06-26',
  '7.1(수) 오리엔테이션, 9.1(화)~9.4(금) 중간평가 등 필수 일정 있음',
  DATE '2026-05-30',
  true,
  true,
  false
WHERE NOT EXISTS (
  SELECT 1
  FROM public.scholarships s
  WHERE s.name = '2026 재능 Dream 희망 장학금'
    AND s.organization = '한국지역난방공사, 굿네이버스'
);
